[package]
name = "wallet-chain-gateway"
version.workspace = true
edition.workspace = true

[[bin]]
name = "wallet-chain-gateway"
path = "src/main.rs"

[dependencies]
wallet-config = { workspace = true }
wallet-error = { workspace = true }
wallet-db = { workspace = true }
salvo = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
reqwest = { workspace = true }
dashmap = { workspace = true }
toasty = { workspace = true }
uuid = { workspace = true }
rand = { workspace = true }
jiff = { workspace = true }
parking_lot = { workspace = true }
