[package]
name = "wallet-sync"
version.workspace = true
edition.workspace = true

[[bin]]
name = "wallet-sync"
path = "src/main.rs"

[dependencies]
wallet-types = { workspace = true }
wallet-error = { workspace = true }
wallet-config = { workspace = true }
wallet-chain = { workspace = true }
wallet-db = { workspace = true }
wallet-events = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }
rust_decimal = { workspace = true }
futures = { workspace = true }
