apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-rpc-urls
  namespace: wallet
data:
  ETH_RPC_URL: "https://eth.llamarpc.com"
  SOL_RPC_URL: "https://api.mainnet-beta.solana.com"
  BTC_RPC_URL: "https://blockstream.info/api"
  DOGE_RPC_URL: "http://wallet-chain-gateway:8545/rpc/doge/gw_5a6ce3f0795246bc9d5b938e5af8a399"
  TRON_RPC_URL: "https://api.trongrid.io"
  CLICKHOUSE_URL: ""
